Repository team-nabi/nabi-market-client, pull requests merged in 2023-12, with the labels that each got.

#145 :tada: 각 리스트 ErrorBoundary, Suspense 적용
  src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
  src/app/(root)/(routes)/cards/components/card-list/CardList.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list/MyCardList.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-list-content/ChatRoomListContent.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-list/ChatRoomList.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsList.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsTemplate.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/notifications/components/notification-list-content/NotificationListContent.tsx
  src/app/(root)/(routes)/notifications/components/notification-list/NotificationList.tsx
  src/app/(root)/(routes)/notifications/components/notification-read-button/NotificationReadButton.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-manager/NotificationStatusManager.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-manager/index.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-tabs/NotificationStatusTabs.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list/MySuggestionList.tsx
  src/components/domain/empty-data-wrapper/EmptyDataWrapper.tsx
  src/components/domain/empty-data-wrapper/index.tsx
  src/components/domain/exception-boundary/ExceptionBoundary.tsx
  src/components/domain/exception-boundary/index.tsx
  src/components/domain/no-data/NoData.tsx
  src/hooks/api/queries/useCardsQuery.ts
Labels: D-0

#147 :sparkles: 마이너 css 변경사항
  src/app/(root)/(routes)/(home)/components/HistorySection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/ui/card/Card.tsx
  src/components/ui/divider/Divider.tsx
Labels: D-1

#151 :sparkles: 이미지 사이즈 최적화
  next.config.js
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/PokeUnavailableInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/image-uploader/components/ImageBlock.tsx
  src/components/domain/logo/Logo.tsx
  src/components/domain/slider/Slider.tsx
  src/components/ui/card/Card.stories.tsx
  src/components/ui/card/Card.tsx
  src/config/imageLoader.ts
  src/hooks/api/mutations/useNotificationUpdateMutation.ts
  src/hooks/useValidate.ts
Labels: D-0

#150 :tada: refresh 로직 추가
  next.config.js
  src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/PokeUnavailableInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/image-uploader/components/ImageBlock.tsx
  src/components/domain/logo/Logo.tsx
  src/components/domain/slider/Slider.tsx
  src/components/ui/card/Card.stories.tsx
  src/components/ui/card/Card.tsx
  src/config/apiEndPoint.ts
  src/config/environment.ts
  src/config/imageLoader.ts
  src/hooks/api/mutations/useNotificationUpdateMutation.ts
  src/hooks/useValidate.ts
  src/lib/fetchAPI.ts
  src/middleware.ts
  src/services/auth/auth.ts
Labels: D-0

#148 :bug: 거래성사된 물건 상세정보페이지 조회 안되는 버그 해결
  src/app/(root)/(routes)/(home)/components/HistorySection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/cards/new/components/PokeAvailable.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestButton.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/loading.tsx
  src/components/domain/badge/trade-complete-badge/TradeCompleteBadge.tsx
  src/constants/card.ts
Labels: D-0

#156 :tada: sitemap 및 robots 추가
  src/app/robots.ts
  src/app/sitemap.ts
  src/types/metadata-interface.d.ts
Labels: D-0

#162 🧪 테스트 코드 작성
  src/lib/fetchAPI.test.ts
  src/utils/getQueryParams.test.ts
  src/utils/getServerCookie.test.ts
  src/utils/getValueByKey.test.ts
  src/utils/isNotNull.test.ts
  tsconfig.json
  vitest.config.js
Labels: D-2
