Repository team-nabi/nabi-market-client, pull requests merged in 2023-10, with the labels that each got.

#3 :tada: 프로젝트 코드 스니펫 작성
  .vscode/settings.json
  .vscode/stories.tsx.code-snippets
  .vscode/test.code-snippets
Labels: D-1

#4 :tada: Nabi 21 버튼 컴포넌트
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/(home)/page.tsx
  src/components/ui/Button/Button.stories.tsx
  src/components/ui/Button/Button.tsx
  src/styles/colors.ts
  tailwind.config.js
Labels: D-1

#6 :memo: 깃헙 템플릿 수정
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/issue-template.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: D-1

#5 :tada: switch 토글 컴포넌트 생성
  package.json
  pnpm-lock.yaml
  src/components/ui/Switch/Switch.stories.tsx
  src/components/ui/Switch/Switch.tsx
  src/components/ui/Switch/index.tsx
Labels: D-1

#8 :tada: Input 및 Label 컴포넌트 작성
  package.json
  pnpm-lock.yaml
  src/components/ui/Input/Input.stories.tsx
  src/components/ui/Input/Input.tsx
  src/components/ui/Input/index.tsx
  src/components/ui/Label/Label.stories.tsx
  src/components/ui/Label/Label.tsx
  src/components/ui/Label/index.tsx
Labels: D-0

#9 :tada: Dialog 컴포넌트 생성
  package.json
  pnpm-lock.yaml
  src/components/ui/Dialog/Dialog.stories.tsx
  src/components/ui/Dialog/Dialog.tsx
  src/components/ui/Dialog/index.tsx
  src/styles/colors.ts
Labels: D-2

#10 :tada: Dropdown 추가
  package.json
  pnpm-lock.yaml
  src/components/ui/DropdownMenu/DropdownMenu.stories.tsx
  src/components/ui/DropdownMenu/DropdownMenu.tsx
  src/components/ui/DropdownMenu/index.tsx
  src/styles/colors.ts
Labels: D-2

#11 :tada: header 컴포넌트 생성
  public/images/bell.svg
  public/images/menu-icon.svg
  src/components/domain/Header/Header.stories.tsx
  src/components/domain/Header/Header.tsx
  src/components/domain/Header/index.tsx
  src/components/domain/Logo/Logo.stories.tsx
  src/components/domain/Logo/Logo.tsx
  src/components/domain/Logo/index.tsx
  src/config/appPath.ts
  src/config/assets.ts
  tailwind.config.js
Labels: D-1

#14 :tada: Avatar 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/ui/Avatar/Avatar.stories.tsx
  src/components/ui/Avatar/Avatar.tsx
  src/components/ui/Avatar/index.tsx
Labels: D-0

#15 :tada: 전체 레이아웃 설정
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/layout.tsx
  src/components/domain/Header/Header.tsx
  src/components/ui/DropdownMenu/DropdownMenu.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: D-1

#16 :tada: 구글, 카카오 로그인 버튼 생성
  .env.example
  public/images/google.png
  public/images/kakao.png
  src/components/domain/buttons/LoginButtons/LoginButtons.stories.tsx
  src/components/domain/buttons/LoginButtons/LoginButtons.tsx
  src/components/domain/buttons/LoginButtons/index.tsx
  src/config/assets.ts
  src/styles/colors.ts
Labels: D-1

#17 🎉 Card 컴포넌트 구현
  src/components/ui/Card/Card.stories.tsx
  src/components/ui/Card/Card.tsx
  src/components/ui/Card/index.tsx
  src/styles/sizes.ts
  tailwind.config.js
Labels: D-1

#13 :tada: Badge 컴포넌트 구현
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Badge/index.tsx
Labels: D-1
