Repository team-nabi/nabi-market-client, pull requests merged in 2023-11, with the labels that each got.

#12 🎉 Tabs 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/ui/Tabs/Tabs.stories.tsx
  src/components/ui/Tabs/Tabs.tsx
  src/components/ui/Tabs/index.tsx
Labels: D-1

#20 :tada: 로그인 UI 생성 및 라우팅 설정
  public/images/logo.svg
  public/images/x-icon.svg
  src/app/(root)/(routes)/(auth)/login/page.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/@authModal/(...)login/page.tsx
  src/app/layout.tsx
  src/components/domain/LoginForm/LoginForm.stories.tsx
  src/components/domain/LoginForm/LoginForm.tsx
  src/components/domain/LoginForm/index.tsx
  src/components/domain/LoginForm/section/LoginButtons.tsx
  src/config/assets.ts
  src/styles/globals.css
Labels: D-1

#23 :tada: Nabi 77 fetch 관련 설정
  .env.example
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/(home)/components/TestBlock.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/layout.tsx
  src/config/apiEndPoint.ts
  src/config/environment.ts
  src/contexts/FetchContext.tsx
  src/contexts/MSWWrapper.tsx
  src/lib/fetchAPI.tsx
  src/lib/msw/mocks/testHandler.ts
  src/services/auth/auth.ts
  src/services/test/test.ts
Labels: D-0

#26 :bug: 최초 접속 시 렌더링 문제
  src/app/(root)/not-found.tsx
  src/app/layout.tsx
  src/contexts/MSWWrapper.tsx
  src/contexts/ThemeProviderContext.tsx
Labels: D-0

#28 :sparkles: fetch class 사용 변경
  src/app/(root)/(routes)/(home)/components/TestBlock.tsx
  src/app/layout.tsx
  src/contexts/FetchContext.tsx
  src/lib/fetchAPI.tsx
  src/services/apiClient.ts
  src/services/test/test.ts
Labels: D-0

#25 🎉 프로필 영역 컴포넌트 구현
  src/app/(root)/(routes)/items/[itemId]/components/ProfileSection/ProfileSection.stories.tsx
  src/app/(root)/(routes)/items/[itemId]/components/ProfileSection/ProfileSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/ProfileSection/index.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/components/ui/Avatar/Avatar.stories.tsx
  src/components/ui/Avatar/Avatar.tsx
  src/constants/image.ts
  src/styles/sizes.ts
Labels: D-0

#24 🎉 TradeStateCard 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/domain/card/trade-state-card/TradeStateCard.tsx
  src/components/domain/card/trade-state-card/index.tsx
  src/components/ui/Card/Card.stories.tsx
  src/components/ui/Card/Card.tsx
  src/types/index.ts
Labels: D-0

#33 :bug: msw가 ssr에서 정상작동하지 않는 문제 처리
  .github/workflows/pull-request.yml
  src/app/(root)/(routes)/(home)/components/TestBlock.tsx
  src/app/layout.tsx
  src/config/environment.ts
Labels: D-0

#30 :tada: oauth mock 생성 및 로그인 로직 연결
  src/components/domain/Header/Header.tsx
  src/components/domain/LoginForm/LoginForm.stories.tsx
  src/components/domain/LoginForm/LoginForm.tsx
  src/components/domain/LoginForm/section/LoginButtons.tsx
  src/config/apiEndPoint.ts
  src/lib/msw/mocks/authHandlers.ts
  src/lib/msw/mocks/handlers.ts
  src/services/auth/auth.ts
Labels: D-1

#21 🎉 Select 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/index.tsx
Labels: D-1

#31 :tada: getItems, itemHandler 구현
  package.json
  pnpm-lock.yaml
  src/config/apiEndPoint.ts
  src/lib/msw/mocks/data/items.json
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/itemHandler.ts
  src/services/item/item.ts
Labels: D-0

#35 🎉 상세정보페이지 ui 최종 완성
  public/images/icon-heart.svg
  public/images/icon-marker.svg
  public/images/icon-money.svg
  public/images/icon-users.svg
  public/images/more-vertical.svg
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/index.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeInfo.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/index.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Button/Button.tsx
  src/components/ui/Card/Card.stories.tsx
  src/components/ui/DropdownMenu/DropdownMenu.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/itemHandler.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/services/item/item.ts
  src/styles/colors.ts
  src/types/index.ts
  src/types/item/index.ts
Labels: D-0

#37 :tada: auth 관련 로직 및 context 제공
  .github/workflows/pull-request.yml
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/domain/Header/Header.tsx
  src/components/domain/Header/section/Avatar.tsx
  src/components/domain/LoginForm/LoginForm.tsx
  src/config/apiEndPoint.ts
  src/config/environment.ts
  src/contexts/AuthProvider.tsx
  src/hooks/useValidate.ts
  src/lib/fetchAPI.tsx
  src/lib/msw/mocks/authHandlers.ts
  src/services/apiClient.ts
  src/services/auth/auth.ts
Labels: D-0

#41 :tada: auth 접근 권한 분리
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/test-auth-only/page.tsx
  src/app/(root)/(routes)/test-not-auth-only/page.tsx
  src/app/layout.tsx
  src/lib/msw/initMockApi.ts
  src/lib/msw/mocks/authHandlers.ts
  src/lib/msw/mocks/handlers.ts
  src/middleware.ts
  src/styles/globals.css
  src/utils/getServerCookie.ts
Labels: D-0

#39 :tada: 제안 모달 컴포넌트 구현
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/components/ui/Dialog/Dialog.tsx
  src/config/apiEndPoint.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/lib/msw/mocks/suggestHandlers.ts
  src/services/suggest/suggest.ts
  src/types/index.ts
Labels: D-0

#40 :tada: 찜 기능 구현
  public/images/icon-heart-active.svg
  public/images/icon-heart-inactive.svg
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/hooks/useDibs.ts
  src/lib/msw/mocks/dibsHandlers.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/services/item/item.ts
  src/types/index.ts
Labels: D-0

#42 🎉 로그인 유무에 따라 보이는 UI 변경
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/lib/msw/mocks/itemHandlers.ts
Labels: D-0

#22 :tada: 이미지 슬라이더 구현
  public/images/icon-left.svg
  public/images/icon-right.svg
  src/components/domain/Slider/Slider.stories.tsx
  src/components/domain/Slider/Slider.tsx
  src/components/domain/Slider/index.tsx
  src/config/assets.ts
Labels: D-1

#46 :tada: 필터폼 UI 및 로직 완성
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/items/components/Item-list/ItemList.tsx
  src/app/(root)/(routes)/items/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/items/components/filter-form-dialog/index.tsx
  src/app/(root)/(routes)/items/components/search-input/SearchInput.tsx
  src/components/domain/card/trade-state-card/TradeStateCard.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/index.tsx
  src/contexts/TanstackQueryContext.tsx
  src/hooks/api/useItemsQuery.ts
  src/hooks/useIntersectionObserver.ts
  src/lib/msw/mocks/data/items.json
  src/lib/msw/mocks/itemHandler.ts
  src/services/item/item.ts
Labels: D-0

#50 :sparkles: 찜 API 업데이트 버전으로 msw 수정
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
  src/hooks/useDibs.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/types/index.ts
Labels: D-1

#52 :tada: 에러 처리
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/(home)/components/TestBlock.tsx
  src/app/(root)/(routes)/(home)/error.tsx
  src/app/(root)/(routes)/test-not-auth-only/page.tsx
  src/app/global-error.tsx
  src/app/layout.tsx
  src/components/domain/Header/section/Avatar.tsx
  src/components/domain/LoginForm/LoginForm.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/Toast/Toaster.tsx
  src/components/ui/Toast/index.tsx
  src/config/appPath.ts
  src/config/errorMessages.ts
  src/hooks/useToast.tsx
  src/lib/errors.ts
  src/lib/fetchAPI.tsx
  src/lib/handleApiError.ts
  src/lib/msw/mocks/authHandlers.ts
  src/services/test/test.ts
  tailwind.config.js
Labels: D-0

#54 :tada: global font 적용
  public/font/Pretendard-Bold.woff
  public/font/Pretendard-Regular.woff
  src/components/ui/Button/Button.tsx
  src/components/ui/DropdownMenu/DropdownMenu.tsx
  src/components/ui/Input/Input.tsx
  src/components/ui/Label/Label.tsx
  src/components/ui/Tabs/Tabs.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: D-1

#53 :tada: 프로필 이미지와 닉네임 변경 컴포넌트 및 로직
  public/images/icon-edit-memo.svg
  public/images/icon-edit.svg
  src/app/(root)/(routes)/mypage/error.tsx
  src/app/(root)/(routes)/mypage/page.tsx
  src/app/(root)/(routes)/mypage/section/UserInfo.tsx
  src/components/domain/AvatarEditable/AvatarEditable.stories.tsx
  src/components/domain/AvatarEditable/AvatarEditable.tsx
  src/components/domain/AvatarEditable/index.tsx
  src/components/domain/TextEditable/TextEditable.stories.tsx
  src/components/domain/TextEditable/TextEditable.tsx
  src/components/domain/TextEditable/index.tsx
  src/components/ui/Input/Input.stories.tsx
  src/components/ui/Input/Input.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/contexts/AuthProvider.tsx
  src/hooks/useValidate.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/userHandlers.ts
  src/services/user/user.ts
  src/types/index.ts
  src/types/user.ts
Labels: D-1

#63 :tada: textarea 추가
  src/components/ui/Textarea/Textarea.stories.tsx
  src/components/ui/Textarea/Textarea.tsx
  src/components/ui/Textarea/index.tsx
Labels: D-0

#57 🎉 카드 삭제 구현 및 코드 정리
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/config/apiEndPoint.ts
  src/hooks/useDibs.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/lib/msw/mocks/suggestHandlers.ts
  src/services/item/item.ts
  src/services/suggest/suggest.ts
  src/styles/globals.css
Labels: D-1

#62 :tada: 이미지 업로더 컴포넌트 작성
  package.json
  public/images/icon-plus.svg
  public/images/icon-x-circle.svg
  src/app/(root)/(routes)/items/[itemId]/components/ProfileSection/ProfileSection.tsx
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/components/domain/ImageUploader/ImageUploader.stories.tsx
  src/components/domain/ImageUploader/ImageUploader.tsx
  src/components/domain/ImageUploader/index.tsx
  src/components/domain/ImageUploader/section/ImageBlock.tsx
  src/components/domain/ImageUploader/section/UploadBlock.tsx
  src/components/ui/Card/Card.tsx
  src/config/assets.ts
  src/constants/image.ts
  src/styles/sizes.ts
Labels: D-1

#64 🎉 이미지 슬라이더 구현 - 상세정보페이지, 홈 배너에 적용
  package.json
  pnpm-lock.yaml
  public/images/Banner1.png
  public/images/Banner2.png
  public/images/Banner3.png
  src/app/(root)/(routes)/(home)/components/HomSlider.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/components/domain/Slider/Slider.stories.tsx
  src/components/domain/Slider/Slider.tsx
  src/components/domain/Slider/index.css
  src/config/assets.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/styles/colors.ts
  src/styles/globals.css
  src/types/item/index.ts
Labels: D-0

#66 :tada: 찔러보기 비허용 구현
  public/images/unavailable.png
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/items/[itemId]/page.tsx
  src/components/ui/Dialog/Dialog.tsx
  src/config/assets.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/lib/msw/mocks/suggestHandlers.ts
Labels: D-0

#51 :tada: 필터 폼 구현(리뷰 사항 반영)
  public/images/filter-active.svg
  src/app/(root)/(routes)/items/components/Item-list/ItemList.tsx
  src/app/(root)/(routes)/items/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/items/components/search-input/SearchInput.tsx
  src/components/domain/card/trade-state-card/TradeStateCard.tsx
  src/components/domain/max-width-wrapper/MaxWidthWrapper.tsx
  src/components/domain/max-width-wrapper/index.tsx
  src/config/assets.ts
  src/hooks/api/useItemsQuery.ts
  src/lib/msw/mocks/data/items.json
  src/services/item/item.ts
  src/types/item/index.ts
Labels: D-1

#65 :tada: 업로드 페이지 컴포넌트, 폼 연결
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/items/[itemId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/items/new/error.tsx
  src/app/(root)/(routes)/items/new/hook/useItemUploadForm.ts
  src/app/(root)/(routes)/items/new/page.tsx
  src/app/(root)/(routes)/items/new/section/CardTitle.tsx
  src/app/(root)/(routes)/items/new/section/Category.tsx
  src/app/(root)/(routes)/items/new/section/Content.tsx
  src/app/(root)/(routes)/items/new/section/ItemImageUploader.tsx
  src/app/(root)/(routes)/items/new/section/ItemName.tsx
  src/app/(root)/(routes)/items/new/section/ItemUploadTemplate.tsx
  src/app/(root)/(routes)/items/new/section/PokeAvailable.tsx
  src/app/(root)/(routes)/items/new/section/PriceRange.tsx
  src/app/(root)/(routes)/items/new/section/TradeArea.tsx
  src/app/(root)/(routes)/items/new/section/TradeType.tsx
  src/app/(root)/(routes)/items/new/section/index.tsx
  src/components/domain/Slider/Slider.tsx
  src/components/ui/Form/Form.tsx
  src/components/ui/Form/index.tsx
  src/config/appValidation.ts
  src/constants/item.ts
  src/types/item/index.ts
Labels: D-1

#61 :tada: 제안 확인 목록 페이지 완성
  public/images/check-circle.svg
  public/images/quit-circle.svg
  src/app/(root)/(routes)/mypage/suggest-checks/components/my-item-summary-card/MyItemSummaryCard.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/my-item-summary-card/index.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-check-card/SuggestCheckCard.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-check-card/index.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-check-list/SuggestCheckList.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-check-list/index.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-status-tabs/SuggestStatusTabs.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/components/suggest-status-tabs/index.tsx
  src/app/(root)/(routes)/mypage/suggest-checks/page.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/hooks/api/useSuggestCheckUpdateMutation.ts
  src/hooks/api/useSuggestChecksQuery.ts
  src/lib/msw/mocks/data/suggest-checks.json
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/suggestCheckHandlers.ts
  src/lib/msw/mocks/suggestHandlers.ts
  src/services/suggest-check/suggestCheck.ts
  src/services/suggest/suggest.ts
  src/types/suggest-check/index.ts
Labels: D-0

#68 :tada: 찜 페이지 목록 구현
  src/app/(root)/(routes)/mydibs/my-dibs-list/MyDibsList.tsx
  src/app/(root)/(routes)/mydibs/my-dibs-list/index.tsx
  src/app/(root)/(routes)/mydibs/page.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/ui/Card/Card.stories.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/queries/useMyDibsQuery.ts
  src/lib/msw/mocks/data/items.json
  src/lib/msw/mocks/data/myDibsItems.json
  src/lib/msw/mocks/dibsHandlers.ts
  src/services/item/item.ts
  src/types/index.ts
Labels: D-0

#67 🎉 거래 제안 로직 구현
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/items/[itemId]/components/trade-section/TradeSection.tsx
  src/components/domain/card/suggest-card/SuggestCard.stories.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/mutations/useSuggestMutation.ts
  src/hooks/api/queries/useSuggestionsQuery.ts
  src/lib/msw/mocks/itemHandlers.ts
  src/lib/msw/mocks/suggestHandlers.ts
  src/services/suggest/suggest.ts
  src/types/index.ts
Labels: D-0

#73 :bug: 카드리스트 렌더링 오류 해결
  src/app/(root)/(routes)/mypage/mycards/components/trade-status-tabs/TradeStatusTabs.tsx
  src/app/(root)/(routes)/mypage/suggestions/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/components/my-suggestion-list/MySuggestionList.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
  src/hooks/api/queries/useMySuggestionsQuery.ts
  src/lib/msw/mocks/cardHandler.ts
  src/lib/msw/mocks/data/cards.json
  src/lib/msw/mocks/data/my-cards.json
  src/lib/msw/mocks/data/suggest-checks.json
  src/lib/msw/mocks/data/suggestions.json
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/myItemHandlers.ts
  src/lib/msw/mocks/suggestCheckHandlers.ts
  src/lib/msw/mocks/suggestionHandlers.ts
  src/services/card/card.ts
  src/services/suggestion/suggestion.ts
Labels: hotfix, D-0

#74 :tada: 카드 업로드 로직 추가 및 카드 수정 페이지 작업
  next.config.js
  src/app/(root)/(routes)/cards/[cardId]/modify/CardModifyTemplate.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/[cardId]/modify/page.tsx
  src/app/(root)/(routes)/cards/new/CardUploadTemplate.tsx
  src/app/(root)/(routes)/cards/new/components/Category.tsx
  src/app/(root)/(routes)/cards/new/components/Content.tsx
  src/app/(root)/(routes)/cards/new/components/ItemImageUploader.tsx
  src/app/(root)/(routes)/cards/new/components/PokeAvailable.tsx
  src/app/(root)/(routes)/cards/new/components/PriceRange.tsx
  src/app/(root)/(routes)/cards/new/components/TradeType.tsx
  src/app/(root)/(routes)/cards/new/components/index.tsx
  src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
  src/app/(root)/(routes)/cards/new/page.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/image-uploader/ImageUploader.tsx
  src/components/domain/image-uploader/components/ImageBlock.tsx
  src/config/apiEndPoint.ts
  src/config/appPath.ts
  src/config/appValidation.ts
  src/lib/msw/mocks/cardHandler.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/imageHandlers.ts
  src/services/card/card.ts
  src/services/images/index.ts
Labels: D-1

#76 :bug: 오퍼하기/찔러보기 요청 관련 에러 해결
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/config/appPath.ts
  src/hooks/api/mutations/useSuggestMutation.ts
  src/lib/msw/mocks/suggestionHandlers.ts
  src/services/suggestion/suggestion.ts
  src/types/suggestion.ts
Labels: D-0

#75 :tada: 내 거래내역 목록 페이지 완성
  public/images/trade-complete.svg
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/index.tsx
  src/app/(root)/(routes)/mypage/histories/page.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/trade-history-card/index.tsx
  src/components/ui/card/Card.stories.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/hooks/api/queries/useMyTradeHistoriesQuery.ts
  src/lib/msw/mocks/data/cards.json
  src/lib/msw/mocks/data/histories.json
  src/lib/msw/mocks/data/my-cards.json
  src/lib/msw/mocks/data/myDibsItems.json
  src/lib/msw/mocks/data/suggestions.json
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/historyHandlers.ts
  src/lib/msw/mocks/suggestionHandlers.ts
  src/services/history/history.ts
  src/types/card.ts
  src/types/tradeHistory.ts
Labels: D-0

#79 :tada: 카드 업로드 버튼 생성
  src/app/layout.tsx
  src/components/domain/buttons/new-card-button/NewCardButton.stories.tsx
  src/components/domain/buttons/new-card-button/NewCardButton.tsx
  src/contexts/TanstackQueryContext.tsx
Labels: D-1

#82 :tada: 각 리스트 페이지 예외처리
  src/app/(root)/(routes)/cards/components/card-list/CardList.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card-list/MyCardList.tsx
  src/app/(root)/(routes)/mypage/mydibs/components/MyDibsList.tsx
  src/app/(root)/(routes)/mypage/suggestions/components/my-suggestion-list/MySuggestionList.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/exception-boundary/ExceptionBoundary.tsx
  src/components/domain/exception-boundary/index.tsx
  src/components/ui/card/Card.stories.tsx
Labels: D-1

#81 :tada: fetch 변경 및 카드 업로드
  next.config.js
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/new/components/Category.tsx
  src/app/(root)/(routes)/cards/new/components/PriceRange.tsx
  src/app/(root)/(routes)/cards/new/components/TradeType.tsx
  src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
  src/components/domain/image-uploader/ImageUploader.tsx
  src/config/appValidation.ts
  src/constants/card.ts
  src/hooks/useValidate.ts
  src/lib/fetchAPI.ts
  src/lib/msw/mocks/handlers.ts
  src/services/auth/auth.ts
  src/services/images/index.ts
  src/utils/isNotNull.ts
Labels: D-0

#80 🎉 최근 거래성사 영역 구현 완성
  next.config.js
  src/app/(root)/(routes)/(home)/components/BannerSection.tsx
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/(home)/components/HistorySection.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/page.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/card/trade-history-card/index.tsx
  src/components/domain/slider/Slider.tsx
  src/config/apiEndPoint.ts
  src/constants/card.ts
  src/constants/pageSize.ts
  src/hooks/api/queries/useRecentHistoryQuery.ts
  src/lib/msw/mocks/data/histories.json
  src/services/history/history.ts
  src/types/card.ts
  src/utils/getValueByKey.ts
Labels: D-0

#84 :bug: 게시글 업로드 및 수정 에러 처리
  public/images/logo-header.svg
  src/app/(root)/(routes)/(home)/components/BannerSection.tsx
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/error.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/[cardId]/modify/page.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/mypage/suggestions/page.tsx
  src/components/domain/logo/Logo.tsx
  src/components/domain/slider/Slider.tsx
  src/config/apiEndPoint.ts
  src/config/assets.ts
  src/lib/fetchAPI.ts
  src/services/card/card.ts
  src/services/images/index.ts
Labels: D-1

#86 🎉 카드 단건, 찜, 제안 카드 api 연결 완료
  public/images/no-data-img.svg
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/(home)/components/HistorySection.tsx
  src/app/(root)/(routes)/(home)/components/PopularCardSection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/mypage/components/UserInfo.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/components/domain/no-data/NoData.tsx
  src/components/domain/no-data/index.tsx
  src/components/ui/card/Card.stories.tsx
  src/config/assets.ts
  src/constants/card.ts
  src/hooks/api/queries/useCardInfoQuery.ts
  src/hooks/useDibs.ts
  src/services/card/card.ts
  src/types/card.ts
  src/types/user.ts
  src/utils/getValueByKey.ts
Labels: D-0

#89 :tada: 각 리스트 조회 페이지 API 연결, 코드 리팩토링
  next.config.js
  src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
  src/app/(root)/(routes)/cards/components/card-list-content/index.tsx
  src/app/(root)/(routes)/cards/components/card-list/CardList.tsx
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/page.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list-content/index.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list/index.tsx
  src/app/(root)/(routes)/mypage/histories/page.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card-list-content/index.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card-list/MyCardList.tsx
  src/app/(root)/(routes)/mypage/mycards/page.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-card/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-list-content/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-list/MySuggestionList.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/my-suggestion-list/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/suggestion-status-tabs/SuggestionStatusTabs.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/components/suggestion-status-tabs/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/page.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
  src/hooks/api/queries/useCardsQuery.ts
  src/hooks/api/queries/useMyCardsQuery.ts
  src/hooks/api/queries/useMySuggestionsQuery.ts
  src/hooks/api/queries/useMyTradeHistoriesQuery.ts
  src/services/card/card.ts
  src/services/history/history.ts
  src/services/suggestion/suggestion.ts
  src/types/card.ts
  src/utils/getQueryParams.ts
Labels: D-1

#85 :tada: 프로필, 닉네임 api 연결
  src/app/(root)/(routes)/mypage/components/UserInfo.tsx
  src/app/(root)/(routes)/mypage/page.tsx
  src/components/domain/header/Header.tsx
  src/components/domain/header/components/AvatarWithDropdown.tsx
  src/components/domain/header/components/MenuButton.tsx
  src/components/domain/header/components/index.tsx
  src/components/domain/image-uploader/ImageUploader.tsx
  src/components/domain/text-editable/TextEditable.tsx
  src/services/card/card.ts
  src/services/user/user.ts
  src/types/user.ts
Labels: D-1

#90 :tada: 접근 권한 처리
  src/app/(root)/(routes)/(home)/error.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/error.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/page.tsx
  src/middleware.ts
  src/services/card/card.ts
Labels: D-0

#92 :tada: 제안 수락, 거절 API 연결 및 기타 작업
  src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
  src/app/(root)/(routes)/cards/page.tsx
  src/app/(root)/(routes)/mypage/histories/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
  src/app/(root)/(routes)/mypage/histories/page.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/mycards/page.tsx
  src/app/(root)/(routes)/mypage/suggestions/[cardId]/page.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-list-content/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-list/MySuggestionList.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-list/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/suggestion-status-tabs/SuggestionStatusTabs.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/suggestion-status-tabs/index.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/page.tsx
  src/components/domain/max-width-wrapper/MaxWidthWrapper.tsx
  src/components/ui/card/Card.tsx
  src/config/apiEndPoint.ts
  src/config/appPath.ts
  src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
  src/services/suggestion/suggestion.ts
Labels: D-0

#88 🎉 오늘의 인기물건 api 연결
  next.config.js
  src/app/(root)/(routes)/(home)/components/PopularCardSection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/(home)/error.tsx
  src/config/apiEndPoint.ts
  src/services/card/card.ts
Labels: D-0

#91 🎉 제안 요청, 카드 삭제 api 연결 완료
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/components/domain/card/suggest-card/SuggestCard.tsx
  src/config/apiEndPoint.ts
  src/config/appPath.ts
  src/hooks/api/mutations/useSuggestionCreateMutation.ts
  src/hooks/api/queries/useSuggestionsQuery.ts
  src/services/suggestion/suggestion.ts
Labels: D-0

#93 :tada: firebase 연결
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/chat/page.tsx
  src/hooks/useFirestoreQuery.ts
  src/lib/firebase/index.ts
Labels: D-1

#94 :bug: 카드 컴포넌트 UI 버그, 무한 스크롤 버그 수정, 각 카드 컴포넌트 key 대신 value 렌더링 하기
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/badge/reserved-badge/ReservedBadge.tsx
  src/components/domain/badge/reserved-badge/index.tsx
  src/components/domain/badge/trade-available-badge/TradeAvailableBadge.tsx
  src/components/domain/badge/trade-available-badge/index.tsx
  src/components/domain/badge/trade-complete-badge/TradeCompleteBadge.tsx
  src/components/domain/badge/trade-complete-badge/index.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/config/apiEndPoint.ts
  src/constants/pageSize.ts
Labels: D-1

#95 :tada: 거래 상태 변경 버튼 구현 및 api 로직 연결 완료
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/mutations/useCardStatusUpdateMutation.ts
  src/services/card/card.ts
Labels: D-1

#96 :tada: 채팅 관련 UI 및 로직
  .hintrc
  public/images/send.svg
  src/app/(root)/(routes)/chat/components/ChatInput.tsx
  src/app/(root)/(routes)/chat/components/ChatList.tsx
  src/app/(root)/(routes)/chat/page.tsx
  src/components/domain/buttons/new-card-button/NewCardButton.tsx
  src/components/domain/page-title/PageTitle.tsx
  src/config/assets.ts
  src/config/firebaseConfig.ts
  src/hooks/useFirestoreQuery.ts
  src/lib/firebase/index.ts
  src/styles/globals.css
  src/types/message.ts
  tailwind.config.js
Labels: D-0

#100 :sparkles: 채팅방 레이아웃 및 타입 조정
  src/app/(root)/(routes)/chat/components/ChatList.tsx
  src/app/(root)/(routes)/chat/page.tsx
Labels: D-1

#103 :tada: 채팅방 api 연결
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatInput.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatList.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatRoomTemplate.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/error.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/app/(root)/(routes)/chatrooms/page.tsx
  src/config/apiEndPoint.ts
  src/middleware.ts
Labels: D-0

#101 :bug: 찜 목록 연결 안되던 오류 해결
  src/app/(root)/(routes)/mypage/mydibs/components/MyDibsList.tsx
  src/app/(root)/(routes)/mypage/mydibs/components/MyDibsTemplate.tsx
  src/app/(root)/(routes)/mypage/mydibs/page.tsx
  src/components/domain/page-title/PageTitle.tsx
  src/config/apiEndPoint.ts
  src/hooks/api/queries/useMyDibsQuery.ts
  src/services/card/card.ts
Labels: D-1

#98 🎉 거래성사요청 기능 구현 완료
  public/images/check-circle.svg
  public/images/quit-circle.svg
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestButton.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestTemplate.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/config/apiEndPoint.ts
  src/constants/card.ts
  src/services/complete-request/completeRequest.ts
  src/types/card.ts
Labels: D-1, 작업 중

#108 🎉 거래성사요청 기능 구현 완료
  public/images/check-circle.svg
  public/images/quit-circle.svg
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestButton.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestTemplate.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/config/apiEndPoint.ts
  src/constants/card.ts
  src/services/complete-request/completeRequest.ts
  src/types/card.ts
Labels: D-0

#109 :tada: 카드 검색 엔터키로 제출 기능 구현
  src/app/(root)/(routes)/cards/components/search-input/SearchInput.tsx
Labels: D-1

#105 :tada: 제안 확인 카드 클릭시 상세정보 페이지로 이동하는 기능 구현
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/config/appPath.ts
Labels: D-1

#111 :tada: useQuery 캐싱 기능 전역 설정 적용
  src/contexts/TanstackQueryContext.tsx
Labels: D-1

#110 :tada: 생성일 부분 '~전' 문자열 추가 구현
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
Labels: D-1

#106 :sparkles: 드롭다운 위치 조정
  src/components/domain/header/components/AvatarWithDropdown.tsx
Labels: D-2

#112 :sparkles: 다크모드 비활성화
  next.config.js
  src/app/layout.tsx
  tailwind.config.js
Labels: D-1

#114 :tada: 각종 링크 추가
  public/images/chat.svg
  public/images/chevron-right.svg
  public/images/heart.svg
  public/images/refresh-ccw.svg
  public/images/shopping-bag.svg
  src/app/(root)/(routes)/mypage/components/Links.tsx
  src/app/(root)/(routes)/mypage/page.tsx
  src/components/domain/header/Header.stories.tsx
  src/components/domain/header/Header.tsx
  src/components/domain/header/components/AvatarWithDropdown.tsx
  src/components/domain/header/components/MenuButton.tsx
  src/config/appPath.ts
  src/config/assets.ts
Labels: D-1

#116 :tada: 알림 api 연결
  .vscode/settings.json
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/app/(root)/(routes)/mypage/components/Links.tsx
  src/app/(root)/(routes)/mypage/mycards/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/header/Header.tsx
  src/components/domain/header/components/AvatarWithDropdown.tsx
  src/components/domain/header/components/MenuButton.tsx
  src/components/domain/header/components/NotificationButton.tsx
  src/components/domain/header/components/index.tsx
  src/components/domain/header/sections/RightSide.tsx
  src/config/apiEndPoint.ts
  src/config/appPath.ts
  src/hooks/api/queries/useNotificationCountQuery.ts
  src/services/notification/notification.ts
Labels: D-0

#115 :tada: 카드 다건 조회 useState, useSearchParams로 교체 및 적용
  src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
  src/app/(root)/(routes)/cards/components/card-list/CardList.tsx
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/components/search-input/SearchInput.tsx
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/max-width-wrapper/MaxWidthWrapper.tsx
  src/config/appPath.ts
  src/hooks/useCreateQueryString.ts
Labels: D-1

#118 :tada: 필터 초기화 버튼 제작 및 기능 구현
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
Labels: D-1

#117 :bug: 내 물건이 아닐때만 찜 가능하도록 변경 + 로그인X상태에서도 물건 정보 보이게 변경
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/DescriptionSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/Dibs.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/contexts/TanstackQueryContext.tsx
  src/hooks/api/queries/useCardInfoQuery.ts
Labels: D-0

#119 :tada: QA - 스타일 관련 변경사항 구현 완료
  public/images/Banner1.png
  public/images/Banner1.svg
  public/images/Banner2.png
  public/images/Banner2.svg
  public/images/Banner3.png
  public/images/Banner3.svg
  public/images/chevron-left.svg
  public/images/icon-edit-memo.svg
  public/images/icon-edit.svg
  src/app/(root)/(routes)/(home)/components/PopularCardSection.tsx
  src/app/(root)/(routes)/(home)/components/Slider.tsx
  src/app/(root)/(routes)/(home)/components/index.css
  src/app/(root)/(routes)/mypage/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/components/domain/page-title/PageTitle.tsx
  src/components/domain/text-editable/TextEditable.tsx
  src/components/ui/tabs/Tabs.tsx
  src/config/assets.ts
  src/constants/image.ts
Labels: D-0

#120 ✨ 랜더링 및 path 변경
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list-content/index.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list/MyCardList.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list/index.tsx
  src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/cards/my/components/my-card/index.tsx
  src/app/(root)/(routes)/cards/my/components/trade-status-tabs/TradeStatusTabs.tsx
  src/app/(root)/(routes)/cards/my/components/trade-status-tabs/index.tsx
  src/app/(root)/(routes)/cards/my/page.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-card/ChatRoomCard.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsList.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsTemplate.tsx
  src/app/(root)/(routes)/dibs/components/index.tsx
  src/app/(root)/(routes)/dibs/page.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list-content/index.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list/MyTradeHistoryList.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list/index.tsx
  src/app/(root)/(routes)/history/page.tsx
  src/app/(root)/(routes)/mypage/components/Links.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/index.tsx
  src/app/(root)/(routes)/notifications/components/notification-list-content/NotificationListContent.tsx
  src/app/(root)/(routes)/notifications/components/notification-list-content/index.tsx
  src/app/(root)/(routes)/notifications/components/notification-list/NotificationList.tsx
  src/app/(root)/(routes)/notifications/components/notification-list/index.tsx
  src/app/(root)/(routes)/notifications/components/notification-read-button/NotificationReadButton.tsx
  src/app/(root)/(routes)/notifications/components/notification-read-button/index.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-tabs/NotificationStatusTabs.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-tabs/index.tsx
  src/app/(root)/(routes)/notifications/page.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/index.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/index.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/index.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list/MySuggestionList.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list/index.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/suggestion-status-tabs/SuggestionStatusTabs.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/suggestion-status-tabs/index.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/page.tsx
  src/app/(root)/(routes)/test-auth-only/page.tsx
  src/app/(root)/(routes)/test-not-auth-only/page.tsx
  src/components/domain/buttons/new-card-button/NewCardButton.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/header/components/MenuButton.tsx
  src/components/domain/header/components/NotificationButton.tsx
  src/config/appPath.ts
Labels: D-0

#124 :tada: 전역적 에러 처리 추가
  src/app/(root)/(routes)/(home)/error.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/error.tsx
  src/app/(root)/(routes)/cards/new/error.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/error.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/app/(root)/(routes)/mypage/error.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/page.tsx
  src/app/(root)/not-found.tsx
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/components/domain/errors/DefaultErrorTemplate.tsx
  src/components/domain/errors/ErrorGateway.tsx
  src/components/domain/errors/ForbiddenErrorTemplate.tsx
  src/components/domain/errors/NotFoundErrorTemplate.tsx
  src/components/domain/header/components/NotificationButton.tsx
  src/config/errorCodes.ts
  src/hooks/useValidate.ts
  src/middleware.ts
Labels: D-0

#126 ✨ 백엔드와 기준 통일 및 불필요한 코드 정리
  src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
  src/app/(root)/(routes)/(auth)/login/google/page.tsx
  src/app/(root)/(routes)/(auth)/login/kakao/page.tsx
  src/app/(root)/(routes)/(home)/components/PopularCardSection.tsx
  src/app/(root)/(routes)/(home)/components/TestBlock.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/description-section/MoreButton.tsx
  src/app/(root)/(routes)/cards/[cardId]/modify/hooks/useCardModifyForm.ts
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/cards/my/components/trade-status-tabs/TradeStatusTabs.tsx
  src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsList.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsTemplate.tsx
  src/app/(root)/(routes)/mypage/components/UserInfo.tsx
  src/app/(root)/(routes)/notifications/components/notification-status-tabs/NotificationStatusTabs.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/suggestion-status-tabs/SuggestionStatusTabs.tsx
  src/components/domain/image-uploader/ImageUploader.tsx
  src/components/domain/text-editable/TextEditable.tsx
  src/config/appValidation.ts
  src/hooks/useDibs.ts
  src/hooks/useToast.tsx
  src/hooks/useValidate.ts
  src/lib/msw/mocks/handlers.ts
  src/lib/msw/mocks/historyHandlers.ts
  src/lib/msw/mocks/suggestionHandlers.ts
  src/middleware.ts
  src/services/card/card.ts
  src/services/suggestion/suggestion.ts
  src/services/user/user.ts
  src/utils/getServerCookie.ts
Labels: D-0

#125 :bug: 거래성사 제안/수락 버그 해결
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/PokeUnavailableInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestButton.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestCard.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/CompleteRequestTemplate.tsx
  src/hooks/api/mutations/useCardStatusUpdateMutation.ts
  src/services/complete-request/completeRequest.ts
Labels: D-0

#129 :tada: favicon 변경
  src/app/favicon.ico
Labels: D-0

#128 :tada: 로딩 구현 및 제안 가능한 카드 get 요청 버그 수정
  package.json
  pnpm-lock.yaml
  public/loading.json
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/SuggestList.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/app/loading.tsx
  src/components/domain/exception-boundary/ExceptionBoundary.tsx
  src/contexts/TanstackQueryContext.tsx
  src/hooks/api/mutations/useSuggestionCreateMutation.ts
  src/hooks/api/queries/useSuggestionsQuery.ts
  src/services/suggestion/suggestion.ts
Labels: D-0

#123 :tada: 낙관적 업데이트 기능 구현, Mutation API 에러 처리 구현
  src/app/(root)/(routes)/cards/components/card-filter-section/CardFilterSection.tsx
  src/app/(root)/(routes)/cards/components/card-filter-section/index.tsx
  src/app/(root)/(routes)/cards/components/card-list-content/CardListContent.tsx
  src/app/(root)/(routes)/cards/my/components/my-card-list-content/MyCardListContent.tsx
  src/app/(root)/(routes)/cards/my/components/trade-status-tabs/TradeStatusTabs.tsx
  src/app/(root)/(routes)/chatrooms/components/chat-room-list-content/ChatRoomListContent.tsx
  src/app/(root)/(routes)/dibs/components/MyDibsTemplate.tsx
  src/app/(root)/(routes)/history/components/my-trade-history-list-content/MyTradeHistoryListContent.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
  src/app/(root)/(routes)/notifications/components/notification-list-content/NotificationListContent.tsx
  src/app/(root)/(routes)/notifications/components/notification-read-button/NotificationReadButton.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-list-content/MySuggestionListContent.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/suggestion-status-tabs/SuggestionStatusTabs.tsx
  src/constants/staleTime.ts
  src/hooks/api/mutations/useMySuggestionUpdateMutation.ts
  src/hooks/api/mutations/useNotificationListUpdateMutation.ts
  src/hooks/api/queries/useCardsQuery.ts
  src/hooks/api/queries/useChatRoomsQuery.ts
  src/hooks/api/queries/useMyCardsQuery.ts
  src/hooks/api/queries/useMyDibsQuery.ts
  src/hooks/api/queries/useMySuggestionsQuery.ts
  src/hooks/api/queries/useMyTradeHistoriesQuery.ts
  src/hooks/api/queries/useNotificationsQuery.ts
  src/types/notification.ts
Labels: D-0

#127 :tada: 각 카드 스타일 수정, 페이지 타이틀 스타일 수정
  src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
  src/app/(root)/(routes)/notifications/components/notification-card/NotificationCard.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-card-description-section/MyCardDescriptionSection.tsx
  src/app/(root)/(routes)/suggestions/[myCardId]/components/my-suggestion-card/MySuggestionCard.tsx
  src/components/domain/card/trade-history-card/TradeHistoryCard.tsx
  src/components/domain/card/trade-status-card/TradeStatusCard.tsx
  src/components/domain/exception-boundary/ExceptionBoundary.tsx
  src/components/domain/page-title/PageTitle.tsx
Labels: D-0

#133 :bug: 토큰 관리 재정의
  src/hooks/useValidate.ts
Labels: hotfix, D-0

#141 ✨ 라우터 조건 및 위치 수정
  src/app/(root)/(routes)/cards/new/hooks/useCardUploadForm.ts
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/components/ChatList.tsx
  src/app/(root)/(routes)/chatrooms/[chatRoomId]/page.tsx
  src/app/layout.tsx
  src/components/domain/header/Header.tsx
  src/components/domain/header/components/AvatarWithDropdown.tsx
  src/components/domain/header/components/MenuButton.tsx
Labels: D-0

#143 :sparkles: 렌더링 및 패치 방식 변경
  src/app/(root)/(routes)/(auth)/login/components/RouteCallback.tsx
  src/app/(root)/(routes)/(home)/components/CategorySection.tsx
  src/components/domain/header/sections/RightSide.tsx
  src/hooks/api/queries/useNotificationCountQuery.ts
  src/hooks/useValidate.ts
Labels: D-0

#135 :tada: 검색 필터 모달 UI 및 기능 변경(일괄적용, 일괄 초기화 버튼 생성)
  src/app/(root)/(routes)/cards/components/filter-form-dialog/FilterFormDialog.tsx
  src/app/(root)/(routes)/cards/my/components/my-card/MyCard.tsx
  src/constants/staleTime.ts
Labels: D-0

#134 :tada: 2차 QA 스타일 수정 완료
  public/images/chevron-left-gray.svg
  src/app/(root)/(routes)/(home)/page.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/ProfileSection/ProfileSection.tsx
  src/app/(root)/(routes)/cards/[cardId]/components/trade-section/TradeInfo.tsx
  src/app/(root)/(routes)/cards/[cardId]/page.tsx
  src/config/assets.ts
Labels: D-0
